Fix gpg-agent for different machines

diff --git a/shell/bashrc b/shell/bashrc
--- a/shell/bashrc
+++ b/shell/bashrc
@@ -49,14 +49,20 @@ if ! shopt -oq posix; then
   fi
 fi
 
+# Set up gpg-agent
+if [ -f "$TCONF/gpg/gpg-agent-info" ]; then
+  . "$TCONF/gpg/gpg-agent-info"
+else
+  >&2 echo "Warning: gpg-agent-info not found. Run:"
+  >&2 echo "  gpg-agent --daemon --enable-ssh-support --write-env-file ~/.gpg-agent-info"
+fi
+
 # Load the config if it exists.
 load() {
   if [ -f "$1" ]; then
     . "$1"
   fi
 }
-
-load "$TCONF/gpg/gpg-agent-info"
 
 # Load modular config
 MODULES="vars functions aliases ps1"
